### ISSUE TITLE
question

### ISSUE THREAD

**Issue by geometry88** [klezVirus/SysWhisper3#10]
supports WINDOWS 11 PRO 22H2??

**Comment by klezVirus** [comment]
Hi @geometry88, I honestly don't know. Let me try and get back to you.

**Comment by Boshommi** [comment]
Can't make it work on Win11 22H2 22621.1265 . Everything works perfect on Win10.

**Comment by klezVirus** [comment]
So, it boils down that the error was due to the limited size of the Syscall table. Should be fixed now. I'll close this but feel free to re-open if needed.
