### ISSUE TITLE
Request for RtlCreateProcessReflection() prototype

### ISSUE THREAD

**Issue by yoda66** [klezVirus/SysWhisper3#12]
Would it be possible to add this function into the mix?  RtlCreateProcessReflection()

**Comment by klezVirus** [comment]
Hi @yoda66 , unfortunately, it is not possible to add functions which are not syscalls. And as you can observe below, RtlCreateProcessReflection is not. :(

![image](https://user-images.githubusercontent.com/8959898/209372340-afba7d30-ba1d-4b4f-92e4-de66348440d3.png)

**Comment by yoda66** [comment]
My apologies, I should have checked.  Thanks for responding and Merry Christmas.

**Comment by klezVirus** [comment]
No apologies needed, no issues at all! All suggestions are precious, so keep them coming! 

Marry Christmas to you as well! ❤️
