### ISSUE TITLE
WOW64 does not work on Windows 11 x64 22H2

### ISSUE THREAD

**Issue by topstrelok** [klezVirus/SysWhisper3#15]
All calls to Nt-api via wow64 on Windows 11 x64 22H2 return status 0xC000000B, on win 10 x64 everything works correctly.

> NtOpenProcess PROC
		push ebp
		mov ebp, esp
		push 0D59FFE03h                  ; Load function hash into ECX.
		call SW3_GetRandomSyscallAddress        ; Get a syscall offset from a different api.
		mov edi, eax                           ; Save the address of the syscall
		push 0D59FFE03h        ; Re-Load function hash into ECX (optional).
		call SW3_GetSyscallNumber
		lea esp, [esp+4]
		mov ecx, 04h
	push_argument:
		dec ecx
		push [ebp + 8 + ecx * 4]
		jnz push_argument
		mov ecx, eax
		mov eax, ecx
		push ret_address_epilog
		call do_sysenter_interrupt
		lea esp, [esp+4]
	ret_address_epilog:
		mov esp, ebp
		pop ebp
		ret
	do_sysenter_interrupt:
		mov edx, esp
		jmp edi
		ret
NtOpenProcess ENDP

**Comment by klezVirus** [comment]
Seems like the error could be associated to the number of syscalls in the x86-wow64 version of Windows 11. The maximum size of the syscall table in SW3 is 500, but the number of syscalls in 32bit (wow64 mode) of Windows 11 is 505. Increasing the size of the syscall table to anything around 550 should solve the issue.

**Comment by Mecanik** [comment]
> Seems like the error could be associated to the number of syscalls in the x86-wow64 version of Windows 11. The maximum size of the syscall table in SW3 is 500, but the number of syscalls in 32bit (wow64 mode) of Windows 11 is 505. Increasing the size of the syscall table to anything around 550 should solve the issue.

Perhaps add this as an improvement?

**Comment by klezVirus** [comment]
And done. Yeah it was quite simple fix, should have done it sooner. Thanks a lot both. Closing this but feel free to reopen if needed ;)
