### ISSUE TITLE
RtlCreateUserThread (last entry in prototypes.json) is not a syscall

### ISSUE THREAD

**Issue by b0rnh4ck** [klezVirus/SysWhisper3#5]
RtlCreateUserThread from prototypes.json is not a syscall and should be removed. (Also the prototype itself is incorrect for x64 usage but that hardly matters.)

**Comment by klezVirus** [comment]
The faulting [commit](https://github.com/jthuraisamy/SysWhispers2/commit/2689d07c8dbe9ca50e76a10076a2c203d977bc0b) was inherited from SW2. Good spot!

**Comment by klezVirus** [comment]
Fixed and closed now!
