### ISSUE TITLE
Potentially unexpected behaviour by using r15 for sysenter

### ISSUE THREAD

**Issue by rickuf** [klezVirus/SysWhisper3#7]
Hi,

## Problem

I'm using the jumper_randomized method for generating the syscalls. The generated stubs are in the following form:

```
NtAllocateVirtualMemory PROC
	mov [rsp +8], rcx          ; Save registers.
	mov [rsp+16], rdx
	mov [rsp+24], r8
	mov [rsp+32], r9
	sub rsp, 28h
	mov ecx, 0C1D1ED76h        ; Load function hash into ECX.
	call SW3_GetRandomSyscallAddress        ; Get a syscall offset from a different api.
	mov r15, rax                           ; Save the address of the syscall
	mov ecx, 0C1D1ED76h        ; Re-Load function hash into ECX (optional).
	call SW3_GetSyscallNumber              ; Resolve function hash into syscall number.
	add rsp, 28h
	mov rcx, [rsp+8]                      ; Restore registers.
	mov rdx, [rsp+16]
	mov r8, [rsp+24]
	mov r9, [rsp+32]
	mov r10, rcx
	jmp r15                                ; Jump to -> Invoke system call.
NtAllocateVirtualMemory ENDP
```

Now I had some code in the following form:

```
//Doing some other stuff beforehand

NtProtectVirtualMemory(hCurrentProc, &pEventWrite, (PSIZE_T)&size,oldprotect, &oldprotect);
void* address = NULL;
NtAllocateVirtualMemory(GetCurrentProcess(), &address, 0, &newSize, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
```

Which workes fine when compiled in Debug mode, but crashed when compiled as a Release build. In Realease mode, `address` was not set to 0, but to a value pointing to some instruction in ntdll.dll. After viewing the code in disassembly, the instruction to zero out the value of `address` was optimized by the compiler to this code: `mov qword ptr [address],r15`, which of course loads the value from our previous syscall into the variable, which in turn leads to problems with the next NtAllocateVirtualMemory call. 

The problem only occurs when some additional code is executed before doing the syscalls. But I don't really want to post the full code here in the issue :D . When the additional code is removed, to program works without problems. I hope that the workarounds are enough for people who are running into the same problem.

## Workaround

There are two possible workarounds I could find while debugging:
* add/remove code to your application until the compiler optimizes in some other way
* change the optimization in the project settings (Project -> Settings -> C++ -> Optimization)

@klezVirus Do you think there is any other way to circumvent this? I guess I ran in a super specific edge case here because of the code optimization. Registers r12-r15 however should be saved and restored before a ret.
`R12..R15 are call-preserved registers you can use for whatever you want, as long as your save/restore them before returning.` (https://stackoverflow.com/questions/53290932/what-are-r10-r15-registers-used-for-in-the-windows-x64-calling-convention)

However, I don't really see a good solution in how this could be done in the stubs.

Cheers

**Comment by klezVirus** [comment]
Hi @rickuf, thanks a lot for that. It might be an edge case, for sure. I'm not sure why the compiler would think r15 is 0 (because this is what is assuming during optimization). 

To address this specific issue, you can add a `xor r15, r15` before returning, but it's not the "correct" way. We should save in memory the value of r15 before storing our `syscall` address, then restore it. Something like the following would save and restore r15 before executing the syscall, by changing the indirect jump with a ROP style return:

```
NtAllocateVirtualMemory PROC
	mov [rsp +8], rcx                       ; Save registers.
	mov [rsp+16], rdx
	mov [rsp+24], r8
	mov [rsp+32], r9
	mov [rsp+40], r15
	sub rsp, 30h
	mov ecx, 0C1D1ED76h                     ; Load function hash into ECX.
	call SW3_GetRandomSyscallAddress        ; Get a syscall offset from a different api.
	mov r15, rax                            ; Save the address of the syscall
	mov ecx, 0C1D1ED76h                     ; Re-Load function hash into ECX (optional).
	call SW3_GetSyscallNumber               ; Resolve function hash into syscall number.
	add rsp, 30h
	mov rcx, [rsp+8]                        ; Restore registers.
	mov rdx, [rsp+16]
	mov r8, [rsp+24]
	mov r9, [rsp+32]
        push r15                                ; push the syscall address on the stack
	mov r15, [rsp+48]                       ; restore r15 with whatever its value was
	mov r10, rcx
	ret                                     ; return to syscall address -> Invoke system call.
NtAllocateVirtualMemory ENDP
```

Note: it should work, but I didn't test that, so might need other tweaks. I'll analyse this and get back to you as soon as I can.

**Comment by extern-c** [comment]
r15 is a non volatile register and so it must be preserved by the callee. You could just use r11 instead. Please see https://github.com/klezVirus/SysWhispers3/pull/11. I tested it with optimizations on  (`/01` and `/02`) and the `Nt`* functions worked as expected.

**Comment by klezVirus** [comment]
Thanks @extern-c, I'm resolving some issues, this was resolved as suggested. Closing this for now, but feel free to reop if needed
