### ISSUE TITLE
x86 cross compile under Linux with mingw assembler errors

### ISSUE THREAD

**Issue by yoda66** [klezVirus/SysWhisper3#8]
Hi @klezVirus,

Not quite sure what I am doing wrong here but I cannot seem to assemble under Linux mingw.   I am doing x86 with mingw target from syswhispers.  Seems like the assembler cannot workout some symbol defs.    See below.

$ python3 syswhispers.py -a x86 -c mingw -f NtCreateThreadEx,NtAllocateVirtualMemory,NtProtectVirtualMemory,NtWriteVirtualMemory,NtOpenProcess,NtClose,NtFreeVirtualMemory -m jumper_randomized -o syscalls_common

$ i686-w64-mingw32-gcc -masm=intel -c syscalls_common.c
/tmp/ccfeQDkK.s: Assembler messages:
/tmp/ccfeQDkK.s:770: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:780: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:784: Error: symbol `do_sysenter_interrupt' is already defined
/tmp/ccfeQDkK.s:811: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:821: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:825: Error: symbol `do_sysenter_interrupt' is already defined
/tmp/ccfeQDkK.s:852: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:862: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:866: Error: symbol `do_sysenter_interrupt' is already defined
/tmp/ccfeQDkK.s:893: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:903: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:907: Error: symbol `do_sysenter_interrupt' is already defined
/tmp/ccfeQDkK.s:934: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:944: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:948: Error: symbol `do_sysenter_interrupt' is already defined
/tmp/ccfeQDkK.s:975: Error: symbol `push_argument' is already defined
/tmp/ccfeQDkK.s:985: Error: symbol `ret_address_epilog' is already defined
/tmp/ccfeQDkK.s:989: Error: symbol `do_sysenter_interrupt' is already defined

**Comment by klezVirus** [comment]
Hi @yoda66, thanks for the bug report. I'm aware of this issue. I'll work on a fix as soon as I can.

**Comment by yoda66** [comment]
Appreciate the acknowledgement @klezVirus so I won't keep trying to debug!  Pretty sure its really a mingw issue but (*sigh*) sometimes we all have to deal with this stuff.  Some threads of mingw optimizer flags seem relevant but I could not get a combo to work.

**Comment by klezVirus** [comment]
This should have been fixed. Closing this for now
